apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: keda-testing-nodejs
spec:
  endpoints:
  - scheme: http              # http/https
    port: 3000-tcp                # Port Name in service
  namespaceSelector: {}
  selector:
    matchLabels:
       app: prometheus        # App Name
